[package]
name = "beginner_1"
version = "0.1.0"
authors = ["OleVoss <57292942+OleVoss@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
